---
name: Titanium.Tizen.Application.Application
summary: "This interface defines the current application's information and the basic operations (such as exit or hide) for the current application."
extends: Titanium.Module
platforms: [tizen]
methods:
  - name: exit
    summary: Exits the current application.

  - name: hide
    summary: Hides the current application. 

  - name: getRequestedAppControl
    summary: Gets the requested application control passed to the current application. 
    description: |
        Gets the requested application control that contains the application control passed by the launchAppControl() method from the calling application.
        The requested application control contains the reason the application was launched and what it has to perform. 
        For example, an application might be launched to display an image on a page by other application's request. 
        In all of these cases, the application is responsible for checking the contents of the application control and responding appropriately when it is launched. 
  - returns: 
      - type: Titanium.Tizen.Application.RequestedApplicationControl
        summary: The details of an requested application control

properties:
  - name: appInfo
    summary: An attribute to store the application information for the current application. 
    type: Titanium.Tizen.Application.ApplicationInformation
    premission: read-only

  - name: contextId
    summary: An attribute to store the ID of a running application. 
    type: String
    premission: read-only
