---
name: Tizen.Application.ApplicationControlData
summary: This interface defines a key/value pair used to pass data between applications through the ApplicationControl interface. 
extends: Titanium.Proxy
platforms: [tizen]

properties:
  - name: key
    summary: An attribute to store the name of a key.   
    type: String

  - name: value
    summary: An attribute to store the value associated with a key.    
    type: "String[]"
